export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const AUTH_REQUEST = 'LOGIN_REQUEST';
export const AUTH_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT="LOG_OUT"